config/routes.rb
Selfstarter::Application.routes.draw do
  root :to => 'preorder#index'
  match '/preorder'               => 'preorder#index', :via => [:get,:post]
  get 'preorder/checkout'
  get 'preorder/aboutus', as: "about"
  get 'preorder/faq', as: "faq"
  get 'preorder/thanks', as: "thanks"
  get 'preorder/flappystory', as: "flappystory"
  match '/preorder/share/:uuid'   => 'preorder#share', :via => :get
  match '/preorder/ipn'           => 'preorder#ipn', :via => :post
  match '/preorder/prefill'       => 'preorder#prefill', :via => [:get,:post]
  match '/preorder/postfill'      => 'preorder#postfill', :via => [:get,:post]
end

app/models/gift_info.rb
class GiftInfo < ActiveRecord::Base
  belongs_to :order, :foreign_key => :uuid

  def from
    self.from_name || self.from_email
  end

  def to
    self.to_name || self.to_email
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  before_validation :generate_uuid!, :on => :create
  belongs_to :user
  belongs_to :payment_option
  has_one :gift_info
  scope :completed, -> { where("token != ? OR token != ?", "", nil) }
  self.primary_key = 'uuid'

  SHIPPING_COST = {
    "United States" => 4.95,
    "Canada"        => 7.95,
    "International" => 12.95
  }

  # This is where we create our Caller Reference for Amazon Payments, and prefill some other information.
  def self.prefill!(options = {})
    @order                = Order.new
    @order.name           = options[:name]
    @order.user_id        = options[:user_id]
    @order.price          = options[:price]
    @order.number         = Order.next_order_number
    @order.payment_option = options[:payment_option] if !options[:payment_option].nil?
    @order.save!

    @order
  end

  # After authenticating with Amazon, we get the rest of the details
  def self.postfill!(options = {})
    @order = Order.find_by!(:uuid => options[:callerReference])
    @order.token             = options[:tokenID]
    if @order.token.present?
      @order.address_one     = options[:addressLine1]
      @order.address_two     = options[:addressLine2]
      @order.city            = options[:city]
      @order.state           = options[:state]
      @order.status          = options[:status]
      @order.zip             = options[:zip]
      @order.phone           = options[:phoneNumber]
      @order.country         = options[:country]
      @order.expiration      = Date.parse(options[:expiry])
      @order.save!

      @order
    end
  end

  def self.next_order_number
    if Order.count > 0
      Order.order("number DESC").limit(1).first.number.to_i + 1
    else
      1
    end
  end

  def generate_uuid!
    begin
      self.uuid = SecureRandom.hex(16)
    end while Order.find_by(:uuid => self.uuid).present?
  end

  # goal is a dollar amount, not a number of backers, beause you may be using the multiple payment options component
  # by setting Settings.use_payment_options == true
  def self.goal
    Settings.project_goal
  end

  def self.percent
    ((Order.revenue.to_f / Order.goal.to_f) * 100).round
  end

  # See what it looks like when you have some backers! Drop in a number instead of Order.count
  def self.backers
    Order.completed.count
  end

  def self.revenue
    if Settings.use_payment_options
      PaymentOption.joins(:orders).where("token != ? OR token != ?", "", nil).pluck('sum(amount)')[0].to_f
    else
      Order.completed.sum(:price).to_f
    end
  end

  validates_presence_of :name, :price, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email

  has_many :orders
end

app/controllers/preorder_controller.rb
class PreorderController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => :ipn


  def index
  end

  def checkout
    @gift = (params[:gift] == "1")
    @error = (params[:e] == "0")
  end

  def aboutus
  end

  def faq
  end

  def flappystory
  end

  def prefill
    if params[:from_email].present?

      @user = User.find_or_create_by(:email => params[:from_email])

      if Settings.use_payment_options
        payment_option_id = params['payment_option']
        raise Exception.new("No payment option was selected") if payment_option_id.nil?
        payment_option = PaymentOption.find(payment_option_id)
        price = payment_option.amount
      else
        price = Settings.price
      end
      price = calculate_price(price)

      @order = Order.prefill!(
        :name => Settings.product_name,
        :price => price,
        :user_id => @user.id,
        :payment_option => payment_option
      )

      # Check for gift settings,
      # sending email notification if valid
      if params[:gift].present? &&
         (params[:from_email].present? && params[:to_email].present?)
        info = GiftInfo.new
        info.from_name  = params[:from_name]
        info.from_email = params[:from_email]
        info.to_name    = params[:to_name]
        info.to_email   = params[:to_email]
        info.note       = params[:note]
        info.order_id   = @order.id
        info.save!
      end

      # This is where all the magic happens. We create a multi-use token with Amazon, letting us charge the user's Amazon account
      # Then, if they confirm the payment, Amazon POSTs us their shipping details and phone number
      # From there, we save it, and voila, we got ourselves a preorder!
      port = Rails.env.production? ? "" : ":3000"
      callback_url = "#{request.scheme}://#{request.host}#{port}/preorder/postfill"
      redirect_to AmazonFlexPay.multi_use_pipeline(
        @order.uuid,
        callback_url,
       :transaction_amount       => @order.price.to_f,
       :global_amount_limit      => @order.price.to_f + Settings.charge_limit,
       :collect_shipping_address => "False",
       :payment_reason           => Settings.payment_description
      )
  else
    redirect_to preorder_checkout_url(:e => 0)
  end
end

  def postfill
    unless params[:callerReference].blank?
      @order = Order.postfill!(params)
    end
    # "A" means the user cancelled the preorder before clicking "Confirm" on Amazon Payments.
    if params['status'] != 'A' && @order.present?
      send_emails!(@order)
      redirect_to :action => :share, :uuid => @order.uuid
    else
      redirect_to root_url
    end
  end

  def share
    @order = Order.find_by(:uuid => params[:uuid])
  end

  def ipn
  end

  private

  def calculate_price(unit_price)
    units    = params[:quantity].try(:to_i) || 0 # default to 0
    locale   = params[:shippingoptions] || "United States"
    shared   = params[:shared] == "1"
    shipping = (shared && locale == "United States") ?
      0.0 : Order::SHIPPING_COST[locale]
    (unit_price.to_f * units) + shipping
  end

  def send_emails!(order)
    info = order.gift_info

    if info.present?
      GiftMailer.confirm(info).deliver!
      GiftMailer.notify(info).deliver!
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logo
    image_tag 'logo.png'
  end
end

app/helpers/preorder_helper.rb
module PreorderHelper

  def like_button(width = 70, show_faces = false)
    raw "<div class=\"fb-like\" data-send=\"false\" data-width=\"#{width}\" data-layout=\"box_count\" data-show-faces=\"true\"></div>"
  end
  def pin_it_button
    image_url = URI.encode("#{request.scheme}://#{request.host}#{image_path(Settings.product_image_path)}")
    raw "<a href='http://pinterest.com/pin/create/button/?url=#{encoded_root_url}&media=#{image_url}' class='pin-it-button' count-layout='vertical'><img border='0' src='//assets.pinterest.com/images/PinExt.png' title='Pin It' /></a>"
  end

  def tweet_button(caption = nil)
    caption ||= "Share on Twitter"
    tweet_text = "Play Flappy Bird with FLAPPY, the wireless toy controller. "
    querystring = {
      :url => "http://www.flappytoy.com",
      :text => tweet_text,
      :via => "flappytoy",
      :count => "vertical"
    }.map { |k, v| "#{k}=#{v}" }.join("&")

    link_to caption, "https://twitter.com/share?#{querystring}", :target => "_blank", :class => "tweet-btn"
  end

  def video_url
    "#{Settings.video_embed_url}?" + case Settings.video_embed_url
    when /vimeo/
      'title=0&byline=0&portrait=0&autoplay=0'
    when /youtube/
      'autohide=1&showinfo=0&rel=0&autoplay=0'
    else
      ''
    end
  end

  def encoded_root_url
    raw URI.encode "#{request.scheme}://#{request.host}/preorder"
  end

  def sold_out(payment_option)
    payment_option.limit > -1 and order_count(payment_option) >= payment_option.limit
  end

  def order_count(payment_option)
    Order.where(payment_option_id: payment_option).count(:token) # count of orders that have a token from amazon and are for this payment option
  end
end

app/views/layouts/_fb.html.erb
<div id="fb-root">
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '623877437667089',
      status     : true,
      xfbml      : true
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="wrapper clearfix">
    <ul>
      <li>
        <a href="#">/faq">Help & FAQs</a>
      </li>
      <li>
        <a href="#">Press & Media</a>
      </li>
      <li>
        <a href="http://blog.lockitron.com/">Blog</a>
      </li>
      <li>
        <a href="#">Privacy Policy</a>
      </li>
      <li>
          <a href="/account/login">Login</a>
      </li>
    </ul>
    <p>© 2009-2012 Apigy Inc. All rights reserved. Patents pending.</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta property="og:title" content="The Flappy Bird wireless toy" />
    <meta property="og:description" content="Flappy is a wireless toy that controls the game when you lift him up. Get Flappy, or send one to a friend!" />

    <title>The Flappy Bird wireless toy</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
  </head>
  <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->
    <%= yield %>
    <%= render 'preorder/footer' %>
    <%= render "layouts/fb" %>
  </body>

</html>

app/views/preorder/_copyright.html.erb
<p class="pull-right-footer">© 2014 ZowPow. All Rights Reserved. MIT License.</p>

app/views/preorder/_footer.html.erb
<div class="footer">
  <div class="wrapper-bottom clearfix">
    <%= render 'preorder/copyright' %>
  </div>
</div>
<%= render 'preorder/google_analytics' %>

app/views/preorder/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Settings.google_id %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/preorder/_header.html.erb
<nav class="flappynav" style="width: 100%; min-width:1024px; background: #fff;">
  <div class="navigationcontainer">
    <div class="navwrapper" style="width:960px; margin:auto;">
    <div class="navbarheader">
      <div id="logo" style=""><%= link_to logo, root_path %></a></div>
    </div>
      <ul class="navright">
         <li class=""><%= link_to 'Meet Flappy', '#meetflappy' %></li>
         <li class=""><%= link_to 'Details', '#details' %></li>
         <li class=""><%= link_to 'FAQ', faq_path %></li>
         <li class=""><%= link_to 'Flappy\'s Story', flappystory_path %></li>
         <li class=""><%= link_to 'About Us', about_path %></li>
         <li class=""><%= link_to 'Checkout', preorder_checkout_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/preorder/_header_other.html.erb
<nav class="flappynav" style="width: 100%; min-width:1024px; background: #fff;">
  <div class="navigationcontainer">
    <div class="navwrapper" style="width:960px; margin:auto;">
    <div class="navbarheader">
      <div id="logo" style=""><%= link_to logo, root_path %></a></div>
    </div>
      <ul class="navright">
         <li class=""><%= link_to 'Meet Flappy', root_path(anchor: 'meetflappy') %></li>
         <li class=""><%= link_to 'Details', root_path(anchor: 'details') %></li>
         <li class=""><%= link_to 'FAQ', faq_path %></li>
         <li class=""><%= link_to 'Flappy\'s Story', flappystory_path %></li>
         <li class=""><%= link_to 'About Us', about_path %></li>
         <li class=""><%= link_to 'Checkout', preorder_checkout_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/preorder/checkout.html.erb
<%= render 'preorder/header_other' %>


<br />
<div class="wrapper-cheq center">
  <h2 class="mid">
  <div>
   <span class="font3"><%=image_tag 'getflahappy.png', alt: 'FLAPPY BIRD' %></span>
  </div>
 </h2>
</div>

 <div class="pull-mid">
   <div class="row">
     <div class="col-md-6"  style="width: 483px;margin-left:-1px; float:left;">
      <div class="leftside-cheq"
      <div class="main_content">
     <div class="imgbig big1"><%=image_tag 'flappy1.jpg', size: '391x275', display: 'none'  %></div>
      <div class="imgbig big2" style="display:none;"><%=image_tag 'flappy2.jpg', size: '391x275', display: 'none'  %></div>
      <div class="imgbig big3" style="display:none;"><%=image_tag 'flappy3.jpg', size: '391x275', display: 'none' %></div>

    <div class="imgthumb thumbnailcurrent" data-id="1" style="margin: 8px 8px 0 0;"><%=image_tag 'flappy1.jpg', size: '120x87'%></div>
      <div class="imgthumb thumbnails" data-id="2" style="margin: 8px 8px 0 0;"><%=image_tag 'flappy2.jpg', size: '120x87'%></div>
      <div class="imgthumb thumbnails" data-id="3"><%=image_tag 'flappy3.jpg', size: '120x87'%></div>
      <br />
      <h5 style="margin-top: 17px;"><br /><br /><br /><br /><br />Flappy comes with the game which will be FREE to download from the iOS App Store and Google Play Store</h5>
      <br />
      <h5><strong>Product Details:</strong></h5>
      <h5>- Flappy is 6.5 x 6 x 4 inches</h5>
      <h5>- He weighs 6 ounces</h5>
      <h5>- He supports <%= link_to 'these devices', faq_path %> and runs on two AAA batteries</h5>
      <h5>- Flappy rates (himself) 4.999 out of 5 stars</h5>
     </div>
    </div>

     <div style="width: 520px; float:right; margin-right:0px; margin-top: -652px;">
      <div class="rightside-cheq"
      <div class="main_content ">
        <% if @error %>
          <div class="flash-error">
            Please enter your email
          </div>
        <% end %>
      <form accept-charset="UTF-8" action="/preorder/prefill" id="checkout" method="post"><div style="margin:0;padding:0;display:inline">
        <%= hidden_field_tag :shared, 0 %>
       <span class="font-cheq">
          I WANT
        <input id="quantity" name="quantity" value="1" style="width: 60px;float: none; " type="number" min="1" required/> FLAPPY'S
      </span>
      <br /><br />
       <span class="font-cheq">SHIP TO</span>
          <select name="shippingoptions" id="shippingoptions">
            <% Order::SHIPPING_COST.each do |locale, price| %>
              <option value="<%= locale %>">
                <%= locale %> -
                <%= "$" + price.to_f.round(2).to_s %>
              </option>
            <% end %>
          </select><br/>
       <br /><br />

       Share with Facebook or Twitter to get free U.S. shipping:
       &nbsp;
       <span class="facebook-btn"><%= image_tag("facebook.png") %></span>
       &nbsp;
       <%= tweet_button image_tag("twitter.png") %>
       <br/><br/>

       <span class="font-cheq">TOTAL</span>
       <div id="totalprice" class="forminput" style="margin-right: 270px; width: 80px;">
        $<%= "%.2f" % (Settings.price + Order::SHIPPING_COST["United States"]) %>
       </div>
       <br /><br />

      <span class="font-cheq">EMAIL</span>
        <%= text_field_tag :from_email, nil, :class => "forminput", :placeholder => "Email", :type => "email", :required => true %>
      <br /><br />

      <span class="font-cheq">
        SEND AS GIFT?
        <%= check_box_tag :gift, :gift, @gift %>
      </span>
      <br /><br />

      <div id="gift-form-section" class="<%= @gift ? '' : 'hidden' %>">
        <div class="font-cheq clearfix">
          From:
          <%= text_field_tag :from_name, nil, :class => "forminput topinput", :placeholder => "Name" %>
        </div>
        <br />
        <div class="font-cheq clearfix">
          To:
          <%= text_field_tag :to_name, nil, :class => "forminput topinput", :placeholder => "Name" %>
          <%= text_field_tag :to_email, nil, :class => "forminput", :placeholder => "Email" %>
        </div>
        <br />
        <div class="font-cheq clearfix">
          Note:
          <%= text_area_tag :note, nil, :class => "forminput", :rows => 5,:placeholder => "Write a message"  %>
        </div>
        <br/>
       <h5 style="text-align: center; margin-top:10px;">Once you click ‘Checkout with Amazon’, we'll notify your friend via email.  Their shipping address will be collected at the end of the campaign.
      </h5></div>

      <input name="utf8" type="hidden" value="&#x2713;" />
      <input name="authenticity_token" type="hidden" value="eHN/nv4yb3/Kk3Cy2NDLOJOCWzv7CWS/YAFopWAMHIg=" /></div>

        <div class="checkout_controls" style="margin-top:-20px;">
          <div class="checkout_controls_wrapper">
            <div class="checkout_controls_inner">

              <input id="preorder" name="preorder" type="hidden" value="true" />
              <input id="amazon_button" name="commit" type="submit" value="Checkout" />
            </div>
          </div>
        </div>
    </form>

      <p style="margin-top:-20px;">
       <h5 style="text-align:center;"> Your payment information will be stored and secure with Amazon Payments. If you don't have an Amazon account, simply select "I'm a new Customer" on the next page.</h5>
       <br />
        <h5><strong>Credit Card Notice</strong></h5>
        <h5>Your card will only be charged if and when the project is successfully funded.</h5>
        <h5><strong>Shipping</strong></h5>
        <h5>Your shipping information will be collected once the campaign is completed and successfully funded. <br/>
The estimated shipping date is May 2014.</h5>
      </p>


    </div>
    <%= render 'preorder/checkout/sidebar' %>
    </div>

  </div>

</div>

<br/><br/>


<div id="backing" style="margin-left:80px; text-align: center;">
<p class="first" style="text-align:center; margin-left: 280px; width: 500px; font-size:30px; text-shadow:none; color:#fff;">Getting there!</p>
<% if Order.revenue.to_f < Order.goal.to_f %>
 <div id="bottomprogress" style=" margin-left: 400px; margin-top:20px">
 <li class="stats statsbg" id="days" style="float:left; margin-left:-80px; margin-top:7px;line-height: .8; text-align:left; color: #fff; font-size: 34px;">

<% if Settings.expiration_date.present? %>
  <%= distance_of_time_in_words_to_now(Settings.expiration_date).gsub(/\D/, "") %>
  <span><%= distance_of_time_in_words_to_now(Settings.expiration_date).gsub(/\d/, "").gsub("about", "") %> left</span>
   <% else %>
   &infin;
  <span style="margin-left: -120px; ">days left</span>
  <% end %>

  <div id='progress_bg' class='small bottomprogressbg'>
    <div id='progress' class='bottomprogress' style='width: <%= Order.percent %>%; float:left'>
    </div><div id='progress_text' style="float: left; margin-top: -7px;"><%= Order.percent %>% <%= Settings.progress_text %></div>
  </div>
 </li>
 <% else %>
   <div id='progress_bg' class='small bottomprogressbg'>
   <div id='progress' class='bottomprogress' style='width: <%= Order.percent %>%; '>
   </div><div id='progress_text' style="float: left; margin-top: -7px;"><%= Order.percent %>% <%= Settings.progress_text %></div>
  </div>
  <% end %>
  </div>
 </div>




</div><br/><br/><br/><br/><br/><br/>

app/views/preorder/homepage/_key_points.html.erb
<div class="wrapper" id="one">

    <h3 class="first">
      Meet Flappy.
    </h3>
     <p class="first-p" id="space">
       He's no ordinary plush toy, he can fly! (well, kind of)
     <p>

    <div class="center">
      <%= image_tag 'meet-flappy.png', size: "500x300" %>
    </div>

</div>


<div class="wrapper" id="two">
  <p class="first-p" id="space">
   <h3 class="first">
     To fly, he needs you to lift him up.
   </h3>
  </p>

  <div class="center" id="space">
    <%= image_tag 'playing-flappy.gif', size: "500x300" %>
  </div>

</div>

<div class="wrapper" id="three">
  <p class="first-p" id="space">
    <h3 class="first">
      Don't let him fall or hit a pipe!
    </h3>
  </p>

  <div class="center" id="space">
    <%= image_tag 'flappy-hits-pipe.gif', size: "500x300" %>
  </div>

</div>

<div class="wrapper" id="four">
  <p class="first-p" id="space">
    <h3 class="first">
      Yes, Flappy can be very VERY difficult to play with:
    </h3>
  </p>

  <div class="center" id="space">
    <%= image_tag 'difficult.gif', size: "500x300" %>
  </div>

</div>

<div class="wrapper" id="four">
  <p class="first-p" id="space">
    <h3 class="first">
      But that’s ok.
    </h3>
    <h3 class="first">
      You can take your frustration out on him.
    </h3>
  </p>

  <div class="center" id="space">
    <%= image_tag 'angry-Jenn.gif', size: "500x300" %>
  </div>

</div>

<div class="wrapper" id="four">
  <p class="first-p" id="space">
    <h3 class="first">
      Which, trust us, is a whole lot better than
    </h3>
    <h3 class="first">
      doing this:
    </h3>
  </p>

  <div class="center" id="space">
    <%= image_tag 'hammer.gif', size: "500x300" %>
  </div>

</div>



<a id="details"></a>

<div class="wrapper" id="five-2">
  <p class="first-p" id="space">

  <h3 class="first"> OK, seriously.</h3>

  <h3 class="first">What is Flappy, the toy game controller?</h3>

  <br />
  <p class="first-p-wide">Flappy is a plush toy that controls the game on your phone or tablet. ‘The game’ is our version of the beloved ‘Flappy Bird’ by Dong Nguyen. To make Flappy fly in the game, you lift up Flappy (the toy)
  </p>

  <div class="center" id="space"></div>

  <div class="center" id="space">
    <%= image_tag 'brian.png' %>
  </div>

  </p>

</div>

<div class="wrapper" id="woah">
  <p class="first-p" id="space">
    <h3 class="first">
    Whoa, that’s cool! How does it work?
    </h3>

      <p class="first-p" id="space">
        Inside of Flappy is a sensor that connects wirelessly to your tablet or mobile device. The sensor detects motion, i.e. lifting Flappy up.
      </p>


      <div class="center" id="space">

        <%= image_tag 'flappy-iphone-ipad.png', size: "570x181" %>

      </div>

  <p class="first-p">Simply launch the game and bring Flappy near your device. Flappy connects automatically. Yep, kind of like magic. Now you’re ready to play!</p>


  <div class="center" id="space"></div>
  <div class="center" id="space"></div>
  <div class="center" id="space"></div>


  <h3 class="first">
    Where do I get the game?
  </h3>
  <p class="first-p">The game will be FREE to download from the iOS App Store and Google Play Store.</p>

  <div class="center" id="space"></div>
  <div class="center" id="space"></div>

  <h3 class="first">
    Which devices does Flappy support?
  </h3>
  <p class="first-p">Most (newer) iOS and Android devices. <%= link_to 'See the full list in our FAQ.', faq_path %></p>

  <div class="center" id="space"></div>
  <div class="center" id="space"></div>

  <h3 class="first">
    Do you have more pictures of Flappy?
  </h3>
  <p class="first-p">Of course. <%= link_to 'Flappy loves Selfies.', 'http://instagram.com/flappythetoy#' %></p>

  <div class="center" id="space"></div>
  <div class="center" id="space"></div>

  <h3 class="first">
    I have a question. What do I do?
  </h3>
  <p class="first-p">Check our <%= link_to 'FAQs.', faq_path %></p>

  <div class="center" id="space"></div>
  <div class="center" id="space"></div>

  <h3 class="first">
    Who are you?
  </h3>
  <p class="first-p"><%= link_to 'Two lost souls.', about_path %></p>

</div>

<div class="wrapper" id="noah" >
</div>

<div class="wrapper" id="ioah">
</div>

<div class="wrapper" id="noah" style="height: 350px;">
</div>

app/views/preorder/homepage/_stats.html.erb
 <div class="pull-mid">
 <div class="row">
  <div id="hometopleft" style=" width: 570px; height: 506px;margin-left: 14px">
     <div id="video">
     <% if Settings.use_video_placeholder %>
     <div class="leftside">
     <div id="video_image">
      <%= image_tag 'video_placeholder.png', size: '550x390', alt: 'video_place_holder' %>
      </div>
      <div id="player" class="hidden" style="display: none;">
        <object width="550" height="390">
          <param name="movie" value="<%= Settings.video_embed_url %>?autohide=1&showinfo=0&rel=0&autoplay=1" />
          <param name="allowFullScreen" value="true" />
          <param name="allowscriptaccess" value="always" />
          <embed src="<%= Settings.video_embed_url %>?autohide=1&showinfo=0&rel=0&autoplay=1" type="application/x-shockwave-flash" width="550" height="390" allowscriptaccess="always" allowfullscreen="true"></embed>
        </object>
      </div>
      <% else %>
      <iframe width='550' height='390' src="<%= video_url %>"></iframe>
    <% end %>
  </div>
  <div class="social-buttons">
    <div class="zocial facebook facebook-btn">Share on Facebook</div>
    <div class="zocial twitter"><%= tweet_button %></div>
  </div>
  <a id="meetflappy"></a>
 </div>
</div>

<div id="hometopright" style="float:right; margin-top:-505px; margin-right:13px;">
<div class="rightside">
<div class="flappy-summary">Flappy is no ordinary plush toy.
He’s wireless and controls the
game when you lift him up.</div>
  <div id="backing">
    <ul>
      <li class="stats" id="backers">
        <%= number_with_delimiter Order.backers, :delimiter => "," %>
        <span><%= Settings.primary_stat %></span>
      </li>
      <li class="stats">
        <%= number_to_currency Order.revenue, :precision => 0 %>
        <span>of <%= number_to_currency Settings.project_goal.to_f, :precision => 0 %></span>
      </li>

      <% if Settings.expiration_date.present? %>
        <li class="stats" id="days">
          <%= distance_of_time_in_words_to_now(Settings.expiration_date).gsub(/\D/, "") %>
          <span><%= distance_of_time_in_words_to_now(Settings.expiration_date).gsub(/\d/, "").gsub("about", "") %> left</span>
        </li>
      <% else %>
        <li class="stats" id="days">
            &infin;
            <span>days left</span>
          </li>
      <% end %>
    </ul>

    <% if Order.revenue.to_f < Order.goal.to_f %>
      <div id='progress_bg' class='small'>
        <div id='progress' class='' style='width: <%= Order.percent + 1 %>%;'>
        </div><div id='progress_text'><%= Order.percent %>% <%= Settings.progress_text %></div>
      </div>
    <% else %>
        <div id="progress_bg" class="small">
        <div id="progress" class="" style="width: 0.0798%;">
        </div>
        <div id='progress_text'><%= Order.percent %>% <%= Settings.progress_text %></div>
    <% end %>

    <hr />

    <div id="reserve_container">
      <p id="ship_date"><%= Settings.ships %></p>
      <a href="/preorder/checkout" class="blue_button reserve"><%= image_tag 'cta-text.png', size: '219x42'%><p class="fifteen">for $15</p></a>
      <p id="price"><%= Settings.price_human %></p>
      <p><%= Settings.dont_give_them_a_reason_to_say_no %></p>
    </div>
    <div class="orange"><%= link_to 'or give Flappy as a gift.', preorder_checkout_path(:gift => 1) %></div>

  </div>
    <p class="pledge">
      This project will only be funded if at least $25,000 is raised by April 8th 2014.
    </p>
  </div>
</div>

</div>
</div>